"""MLflow experiment-tracking helpers, reused by every week's experiments.

Local, file-based tracking store under `mlruns/` at the repo root — gitignored,
same as `data/` and `reports/`: it's regenerated by rerunning the experiment
notebooks, not something to commit. One MLflow *experiment* per forecast
horizon (`edf.config.HORIZONS`), since metrics aren't comparable across
horizons (see `edf.config`'s docstring) — keeping them in separate experiments
stops the MLflow UI from sorting a 30-minute-ahead MAE next to a 7-day-ahead
one as if they were on the same scale. Baselines *and* models share the same
per-horizon experiment (not split further), since being directly comparable
within a horizon is exactly the point.
"""

from __future__ import annotations

from pathlib import Path

import mlflow
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
MLRUNS_DIR = REPO_ROOT / "mlruns"
# MLflow 3's plain filesystem backend ("file:...") is in maintenance mode and
# raises unless explicitly opted into — a local sqlite db is the supported
# equivalent for a single-user, no-server setup.
DEFAULT_TRACKING_URI = f"sqlite:///{MLRUNS_DIR / 'mlflow.db'}"

METRIC_COLUMNS = ("mae", "rmse", "mape", "mase")


def experiment_name(horizon_name: str) -> str:
    return f"forecast-{horizon_name}"


def log_model_run(
    horizon_name: str,
    horizon_periods: int,
    model_name: str,
    fold_metrics: pd.DataFrame,
    tracking_uri: str | None = None,
    extra_tags: dict[str, str] | None = None,
) -> None:
    """Log one (horizon, model) run: per-fold metric curves plus their mean.

    `fold_metrics` is one model's per-year rows from
    `edf.evaluate.compare_models` (index: year; columns: mae/rmse/mape/mase),
    e.g. `results.xs(model_name, level="model")`. Per-fold values are logged
    with `step=year` so MLflow can plot them as a curve; `mean_*` keys hold
    the aggregate used for cross-model/cross-horizon comparison, kept
    separately named so they aren't mistaken for "the last fold's value".
    `extra_tags` (e.g. `{"strategy": "recursive"}`) is merged in alongside
    the standard horizon/model tags, for runs that need another dimension to
    stay distinguishable within one horizon's experiment.
    """
    if tracking_uri is None:
        MLRUNS_DIR.mkdir(parents=True, exist_ok=True)
    mlflow.set_tracking_uri(tracking_uri or DEFAULT_TRACKING_URI)
    mlflow.set_experiment(experiment_name(horizon_name))

    with mlflow.start_run(run_name=model_name):
        mlflow.set_tags({"horizon": horizon_name, "model": model_name, **(extra_tags or {})})
        mlflow.log_param("horizon_periods", horizon_periods)
        mlflow.log_param("n_folds", len(fold_metrics))

        present_columns = [c for c in METRIC_COLUMNS if c in fold_metrics.columns]
        for year, row in fold_metrics.iterrows():
            for column in present_columns:
                value = row[column]
                if pd.notna(value):
                    mlflow.log_metric(column, float(value), step=int(year))

        means = fold_metrics[present_columns].mean()
        mlflow.log_metrics({f"mean_{name}": float(value) for name, value in means.items()})
